spring:
  application:
    name: security
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: mysecretkey123456789012345678901234567890123456 # min 256-bit key for HS256
  expiration: 3600000 # 1 ???